### ISSUE TITLE
> Feel free to re-open if any further info.

### ISSUE THREAD

**Issue by babawarrior** [sipsorcery-org/sipsorcery#1208] opened 2024-11-02 22:34 UTC
> Feel free to re-open if any further info.

I'm having a issue where I just receive "Call Result Failure" when using SIPCallDescriptor.
`
        const string DESTINATION = "sip:46735000000@sip.diamondcard.us";
        const string from = "46735000000\<480000@sip.diamondcard.us>";
        SIPCallDescriptor callDescriptor = new SIPCallDescriptor("314444", "438800000", DESTINATION, from, null, null, null, null, 
       SIPCallDirection.Out, "application/sdp", null, null);

`

_Originally posted by @babawarrior in https://github.com/sipsorcery-org/sipsorcery/issues/1152#issuecomment-2453212966_

**Comment by sipsorcery** [comment] 2024-11-02 22:36
Duplicate of #1152.

**Closed by sipsorcery** 2024-11-02 22:36 UTC
Labels: duplicate
