### ISSUE TITLE
not receiving voice frames  

### ISSUE THREAD

**Issue by RehamAbbady** [sipsorcery-org/sipsorcery#517] opened 2021-07-06 09:52 UTC
hello, I'm trying to do a project similar to this one 
https://github.com/sipsorcery-org/sipsorcery/blob/master/examples/WebRTCExamples/WebRTCReceiveAudio/Program.cs
where i receive audio from an rtc service broadcast 
and although the connection is done correctly, OnRtpPacketReceived never gets triggered 
also,
`WindowsAudioEndPoint windowsAudioEP = new WindowsAudioEndPoint(new AudioEncoder(), -1, -1, true, false);
                MediaStreamTrack audioTrack = new MediaStreamTrack(windowsAudioEP.GetAudioSinkFormats(), MediaStreamStatusEnum.RecvOnly);
                pc.addTrack(audioTrack); `
would WindowsAudioEndPoint work on linux? and if not, what's the alternative?

**Comment by sipsorcery** [comment] 2021-07-07 20:49
The `WindowsAudioEndPoint` class won't work on Linux. It relies on the `NAudio` package which is Windows specific. You could take a look at the [PortAudio](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/SIPExamples/GetStartedPortAudio) example instead. It was intended as a way to use this library with audio on Linux. Unfortunately it doesn't seem to have worked very well for many people and using audio on Linux with .NET turned out to be surprisingly tricky. 

Other than that the first thing I'd recommend checking is that the audio packets are being received by your machine. The easiest way to do that is to use WireShark with a capture filter along the lines of:

`udp portrange 49000-65535`

**Comment by SeaLife** [comment] 2021-07-08 16:56
Hey, 

im also encountering this issue.. Im using docker to run my application:

```
FROM mcr.microsoft.com/dotnet/runtime:5.0

# APT (libopus, ffmpeg)
RUN apt-get update && apt-get install -y libopus-dev ffmpeg && rm -rf /var/lib/apt/lists/*

# INSTALL APP
WORKDIR /App
COPY DiscordSIPProxy/bin/Release/net5.0 /App

# RUN APP
CMD [ "dotnet", "DiscordSIPProxy.dll" ]
```

I just want to "redirect" my voice to a discord voice stream...

But for some reason, the RTP packages only go up to 24 packages and stop...

![image](https://user-images.githubusercontent.com/6567620/124961845-3c492780-e01e-11eb-8b7a-9de89b111203.png)

**Comment by sipsorcery** [comment] 2021-07-08 19:37
The RTP session will close itself if no RTCP packets are received within any 30s period. This is a defensive measure. Without it an RTP session would potentially stay alive and waiting forever. A favourite mechanism of SIP scanning tools is to initiate calls without ever bothering to set up RTP. If there isn't some timeout mechanism you'll quickly find your machine's memory all used up.

The first thing to do is to try and find out if the remote party is sending RTP packets. WireShark (or tshark or tcpdump if running in Docker) are good for that. It is strange that you get so few RTP packets in 30s do perhaps you are using some kind of custom sender?

Other than that you can build the sipsorcery library from source and change the [RTCP session timeout](https://github.com/sipsorcery-org/sipsorcery/blob/10ed1071dea626e3648f98bd19cb5d17f7b091e7/src/net/RTCP/RTCPSession.cs#L61) to a larger value to see if that helps.

**Comment by RehamAbbady** [comment] 2021-07-13 07:16
Wireshark does show that I'm receiving packets, and no I'm not using a costume sender, I've also noticed that the connection state is always new, it never changes, given that ice gathering state is complete.

**Comment by sipsorcery** [comment] 2021-07-13 13:24
I the "rtc service broadcast" you are attempting to receive from a public source? If so can you provide the details and I can take a look.

You can also run some basic connectivity checks using the [webrtccmdline](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/webrtccmdline) application to check things like your firewall, NAT etc.

`examples\webrtccmdline> dotnet run -- --echo https://sipsorcery.cloud/janus/echo/offer --stun stun:sipsorcery.com`

If it works you should see a bunch of debug messages and close to the end 

`[14:23:06 DBG] Peer connection state changed to connected.`

**Comment by RehamAbbady** [comment] 2021-07-13 17:31
the rtc service

 i'm using is millicast 
https://www.millicast.com/
i tried running webrtccmdline 
and after the connection state changed to connected i got these warnings and errors
![Screenshot (55)](https://user-images.githubusercontent.com/59123535/125498590-33c24a3d-8be5-42eb-a982-7f19a2ec045f.png)

**Comment by SeaLife** [comment] 2021-07-13 18:37
I've had the same issue with not receiving RTP events at all, on my end, it was something weird going on with my network...
I deployed my application onto a remote machine with public ip, it worked right away...

I also noticed, it worked on my windows machine after altering the windows firewall, but it would not work at all (at least i was not able to get it working) on my Linux VM...

So maybe its a network related issue and not a software problem.

**Comment by sipsorcery** [comment] 2021-07-13 20:17
> and after the connection state changed to connected i got these warnings and errors

It seems like the peer connection gets established and is then dropped when the sipsorcery end does not respond to the STUN messages it doesn't understand. The `SRTCP unprotect` error is also concerning but that shouldn't cause a connection drop.

I had a quick look at the millicast sight. The most [relevant webrtc example](https://dash.millicast.com/docs.html?pg=how-to-broadcast-in-js#how-to-view-sect) I found was very lengthy. Do you have a test stream and sample code I can use to replicate the issue?

**Comment by RehamAbbady** [comment] 2021-07-15 10:09
I changed these two lines
`WindowsAudioEndPoint windowsAudioEP = new WindowsAudioEndPoint(new AudioEncoder(), -1, -1, true, false); MediaStreamTrack audioTrack = new MediaStreamTrack(windowsAudioEP.GetAudioSinkFormats(), MediaStreamStatusEnum.RecvOnly); pc.addTrack(audioTrack);`
to this 
` var audioFormat = new SIPSorceryMedia.Abstractions.AudioFormat(SIPSorceryMedia.Abstractions.AudioCodecsEnum.OPUS, 13);
            MediaStreamTrack audioTrack = new MediaStreamTrack(audioFormat, MediaStreamStatusEnum.RecvOnly);`
            
            and now the connection state changes to connected, but still no voice frames received 
            i've uploaded a sample code with a working stream on it [here](https://github.com/RehamAbbady/WebRTCReceiveAudio)
            if you want to take a look

**Comment by sipsorcery** [comment] 2021-07-15 15:12
The good news is I found and fixed a bug, see link just above, that was preventing the DTLS handshake completing when the remote party wanted to be the DTLS server (the millicast server is using ice-lite and it's the first time I've come across that). If you pull the latest code from `master` you should now be able to get your example to establish the ICE connection, complete the DTLS handshake and start receiving RTP.

The bad news is the sipsorcery library does not have an OPUS audio codec option so you'll need to find and plug another library in so you can decode the RTP packets. I did try your example with `PCMU` and `G722` but the millicast server didn't seem to like that.

Using either of the audio formats below resulted in the millicast server responding with an SDP answer with 0 supported audio codecs.

`var audioFormat = new SIPSorceryMedia.Abstractions.AudioFormat(SIPSorceryMedia.Abstractions.SDPWellKnownMediaFormatsEnum.PCMU);`
 `var audioFormat = new SIPSorceryMedia.Abstractions.AudioFormat(SIPSorceryMedia.Abstractions.SDPWellKnownMediaFormatsEnum.G722);`

**Comment by RehamAbbady** [comment] 2021-07-16 12:59
i'm now receiving packets after pulling the latest library code, thank you!

**Comment by RehamAbbady** [comment] 2021-07-26 11:32
hello, I have a follow up question about the audio formats
is the payload encoding dependent on the audio format that is passed to the audiotrack?
```
var audioFormat = new SIPSorceryMedia.Abstractions.AudioFormat(SIPSorceryMedia.Abstractions.AudioCodecsEnum.OPUS,13);
            MediaStreamTrack audioTrack = new MediaStreamTrack(audioFormat, MediaStreamStatusEnum.RecvOnly);

```
for example, if the stream i'm receiving has a sample rate of 16000 and my audioformat.ClockRate is set to 48000, will the the voice frames that I'm receiving be faulty?
i'm trying to write the rtp packets payload i'm receiving to an opus file, no matter how i  change the sample rate of the audio format and the opus writer I always get noisy files without any trace of the original sound of the stream.
when i tried to record the payload in this [example](https://github.com/sipsorcery-org/sipsorcery/tree/master/examples/WebRTCExamples/WebRTCReceiveAudio)
and it worked, so I'm guessing that the problem might be related to the audioformat i'm using

**Comment by sipsorcery** [comment] 2021-07-26 11:47
> is the payload encoding dependent on the audio format that is passed to the audiotrack?

Yes.

> for example, if the stream i'm receiving has a sample rate of 16000 and my audioformat.ClockRate is set to 48000, will the the voice frames that I'm receiving be faulty?

Typically if the sample rate is wrong you can still make out a few words or a bit of music but it's too fast or slow.

> so I'm guessing that the problem might be related to the audioformat i'm using

You can catch the [RTPSession.OnAudioFormatsNegotiated](https://github.com/sipsorcery-org/sipsorcery/blob/e962e9897ba5c15d7f4a26a7c9fbfd1f553b9005/src/net/RTP/RTPSession.cs#L387) event to know which format the two ends of the call agreed upon.

**Comment by RehamAbbady** [comment] 2021-07-29 11:44
I keep getting this warning
 An RTP packet with SSRC 596118324 and payload ID 127 was received that could not be matched to an audio or video stream.
 is there a way I can handle those type of packets? other than OnRtpPacketReceived, because it doesn't seem to catch them

**Comment by sipsorcery** [comment] 2021-07-29 11:55
Ideally you want to track down what the RTP packet is and why it's not being recognised. If it's not required maybe your `MediaStreamTracks` are using `sendrecv` instead of `sendonly` or something like that.

If you look at the SDP you get from the remote peer it will tell you what audio or video format is using RTP payload ID 127.

**Comment by RehamAbbady** [comment] 2021-07-29 12:26
millicast keeps sending dynamic rtp packets with payload type 127, it's supposed to be opus, according to the sdp answer, and I think these are the voice packets i'm trying to receive, but for some reason they're not caught by the OnRtpPacketReceived event handler

**Comment by sipsorcery** [comment] 2021-07-29 12:29
Try setting your `OPUS` payload ID to `127`:

````
var audioFormat = new SIPSorceryMedia.Abstractions.AudioFormat(SIPSorceryMedia.Abstractions.AudioCodecsEnum.OPUS, 127);
````

**Comment by RehamAbbady** [comment] 2021-07-29 12:43
well, I tried, but millicast server didn't seem to like that, it didn't connect.

**Comment by sipsorcery** [comment] 2021-07-29 19:06
Maybe #534 was causing a problem? It's fixed on `master` now.

If not you would need to try and track down why the sipsorcery end and millicast ends can't agree on the `OPUS` payload ID.

**Comment by RehamAbbady** [comment] 2021-08-01 12:19
no, that wasn't the problem.
i noticed that the sdp answer is missing a=rtpmap attribute, can that cause a problem? and why would that happen?

**Comment by sipsorcery** [comment] 2021-08-14 08:30
Closing, feel free to re-open if there is any further information.

**Closed by sipsorcery** 2021-08-14 08:30 UTC
Labels: bug
